apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app2.fullname" . }}
  labels:
    {{- include "app2.labels" . | nindent 4 }}
data: 
  nginx.conf: '
events {
}
http {
   server {
       listen 80;
       location / {
          return 200 "Hello world from {{ include "app2.fullname" . }}!";
       }
   }
}
'