apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
  - repoURL: 581349712378.dkr.ecr.us-east-1.amazonaws.com
    targetRevision: "20230626054224"
    chart: app1

    helm:
      valueFiles:
      - $values/helm/app1/values_dev.yaml
  - repoURL: https://github.com/Mark-Rayhshtat/argocd_multiple_sources.git
    targetRevision: main
    ref: values
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true