name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Get all changed apps
        id: changed-files-yaml
        uses: tj-actions/changed-files@v37
        with:
          files_yaml: |
            app1:
              - helm/app1/**
              - !helm/app1/values.yaml
              - !helm/app1/values_dev.yaml
            app2:
              - helm/app2/**
              - !helm/app2/values.yaml
              - !helm/app2/values_dev.yaml
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Some AWS commands
        run: |
          aws ecr describe-registry --region us-east-1
      - name: Run step if app1 file(s) change
        if: steps.changed-files-yaml.outputs.app1_any_changed == 'true'
        run: |
          echo "One or more app1 file(s) has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-yaml.outputs.app1_all_changed_files }}"
      - name: Run step if app2 file(s) change
        if: steps.changed-files-yaml.outputs.app2_any_changed == 'true'
        run: |
          echo "One or more app2 file(s) has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-yaml.outputs.app2_all_changed_files }}"
      
